name: main

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        #run: mvn --batch-mode --update-snapshots verify
      #- run: npm ci
      #- run: npm run build --if-present
      #- run: npm test
          
